apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: level-uphaken
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
  selector:
    service: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: level-uphaken
spec:
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
        - image: git.haw-hamburg.de:5005/level-uphaken/level-uphaken/frontend:latest
          name: frontend
          env:
          - name: API_ENDPOINT
            value: http://backend:8080/api/v1
          - name: PUBLIC_API_ENDPOINT
            value: https://level-uphaken.informatik.haw-hamburg.de/api/v1
          - name: NEXTAUTH_URL
            value: https://level-uphaken.informatik.haw-hamburg.de
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: frontend-secrets
                key: jwt-secret
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: frontend-secrets
                key: jwt-secret
          - name: JWT_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: frontend-secrets
                key: jwt-signing-key
          - name: JWT_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: frontend-secrets
                key: jwt-encryption-key
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: pull-secret
