apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: level-uphaken
stringData:
  jwt-secret: <token>
  mysql-root-password: <password>
  mysql-password: <password>
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: level-uphaken
stringData:
  jwt-secret: <token>
data:
  jwt-signing-key: <base64-json-object>
  jwt-encryption-key: <base64-json-object>